### ISSUE TITLE
Error: undeclared identifier: 'typedArray'

### ISSUE THREAD

**Issue by xix-xeaon** [godot-nim/gdext-nim#103]
When trying to import `gdext/classes/gdsurfacetool.nim` or `gdext/classes/gdarraymesh.nim` you get the error

`Error: undeclared identifier: 'typedArray'`

for the functions `addTriangleFan` and `addSurfaceFromArrays`, respectively. Several other files seem to have the same problem.

**Comment by panno8M** [comment]
Thanks for the report.
I should have checked to see if the class is compilable even if it is not used for testing.
All classes are currently compilable.

**Comment by xix-xeaon** [comment]
Confirmed these classes can now be imported. Thanks!
