### ISSUE TITLE
Usage Guide / Godot Translation / Documentation

### ISSUE THREAD

**Issue by xix-xeaon** [godot-nim/gdext-nim#105]
Installation was easy enough, but it's difficult to know how to translate code/concepts from GDScript to gdext-nim, or figuring out how to use it. I'm looking at your [demo examples](https://github.com/godot-nim/demo) and that's of course helpful but a proper guide is needed for a beginner to understand quickly.

Here's what I got so far (might be wrong) as an example:

You can't attach a nim-script to a node - you have to create and register classes like with `class_name` and then create that that class-node. Add your class-level variables to the type. Use the pragma `{.gdexport.}` to make them accessible in the inspector.
```nim
type MyClass* = ptr object of Node3D
    score :int = 0
    mob_scene* {.gdexport.} :GdRef[PackedScene]
    player* {.gdexport.} :Node3D
```
You can reference the datatypes of all Godot classes as long as you've imported `gdext`, but in order to use their methods and properties you need to import the actual class, which is located in `gdext/classes/` with the names beginning with _gd_.
```nim
import gdext/classes / [gdNode3D]
```
For your class you'll mostly want to create routines which take as their first argument the type of your class. The `gdsync` pragma allows hotreloading? If you're overloading routine then it needs to be a `method` and not start with _.
```nim
method ready(self :MyClass) {.gdsync.} = discard
proc do_thing(self :MyClass) {.gdsync.} = discard
```
Your code will run in the editor as well (like with the `@tool` annotation), use `Engine.isEditorHint` to check.
```nim
method process(self :MyClass, delta :float) {.gdsync.} =
    if Engine.isEditorHint: return
    # the following code will not run in the editor
```
There's syntax to reference nodes in the scene like with dollar-sign ($), but I think it could be improved. I don't know about unique name; percentage (%).
```nim
let node = self/"Path"/"to"/"Node" as Sprite2D
let other_node = self.getNode("Path/to/ThisNode") as MeshInstance3D
```
Builtin global functions have the same names. Types like **Vector3** etc do not need to be imported and work like in GDScript, but the constructor is lower case and names are technically Capitalized instead of UPPERCASE - nim of course allows uppercase anyway.
```nim
self.position = vector3(0, 0, 0) + Vector3.Down + Vector3.DOWN
print self.position.length
```
Create new instances of nodes using `instantiate`, with an optional name for the node.
```nim
let node :Node3D = Node3D.instantiate "some name"
node.position = vector3(0, 0, 3)
self.add_child(node)
```
Nodes, and some other things, ultimately inherit from `Object` and their types are simple. Others inherit from `RefCounted` which means they're encapsulated with _GdRef_. If you need access to the plain datatype without _GdRef_ they can be dereferenced with `[]`.
```nim
let mi :MeshInstance = instantiate MeshInstance # Object type
let st :GdRef[SurfaceTool] = instantiate SurfaceTool # RefCounted type
st[].begin(primitiveTriangles) # st needs dereferencing
let m :GdRef[ArrayMesh] = st[].commit()
mi.mesh = m as GdRef[Mesh] # Casting to super type
```
Also note, builtin enums (like `Mesh.PRIMITIVE_TRIANGLES` in this case) are slightly different from Godot; look for them in `gdext/gen/globalenums.nim` and `gdext/gen/localenums.nim`.

I haven't gotten to signals yet.. Look at Dodge the Creeps demo.

**Comment by panno8M** [comment]
I would like to post this as a wiki, can you help?

I can offer two ways:

* Join godot-nim org and compile a wiki

  I would like to leave the organization to you if possible, but if necessary, I can create a template for you.

* Continue to edit this Issue and I will reflect it in the wiki sequentially

In any case, we will credit you in the relevant section of the wiki and in the project readme. How about it?

**Comment by xix-xeaon** [comment]
I might as well join and edit the wiki =)

**Comment by panno8M** [comment]
We have sent you an invitation. You probably received it to your registered email on github.

The wiki is provided by github: https://github.com/godot-nim/gdext-nim/wiki
We do not have a specific structure for the wiki as a whole, but we recommend that the guide be single-page.
The github wiki indexes header elements directly in the sidebar, so please set the header with appropriate granularity.

FYI:
* [Basic writing and formatting syntax][1]
* [Adding or editing wiki pages][2]

[1]:  https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
[2]: https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages

**Comment by xix-xeaon** [comment]
The wiki has been updated.

**Comment by panno8M** [comment]
Awesome work!
Btw there are some less common code in the guide, can you just fix that?
(Here we assume that `nimpretty` format is what is common.)

Replacement rule: ` :Type` -> `: Type`
Examples: 
```diff
 type MyClass* = ptr object of Node3D
<    score :int = 0
>    score: int = 0
<    mob_scene* {.gdexport.} :GdRef[PackedScene]
>    mob_scene* {.gdexport.}: GdRef[PackedScene]
<    player* {.gdexport.} :Node3D
>    player* {.gdexport.}: Node3D
```

**Comment by xix-xeaon** [comment]
Yeah, I always write `name :type` and similar. The colon specifies a type so it makes sense that it's "attached" to the type and not the name. But I can change it to the common style.

I think `GdRef[T]` is more clear as a type, while `gdref T` looks more like a command, or other special keyword. I know you've chosen the latter in your source. I assume that's because you're emulating of the real keyword `ref` but for Godot. On one hand it's ergonomic to think of it that way, on the other hand it's confusing because it is actually not.

I'm not sure, but if `gdref T` does work just like `ref` in all cases without any gotchas then I think it can be good. It just made it clearer to me as `GdRef[T]` while I was figuring out the difference between Objects and RefCounted.

**Comment by panno8M** [comment]
> But I can change it to the common style.

Considering, I don't think the position of the colon would confuse users. I will respect your style.

#### About GdRef - gdref

Thank you for sharing your thoughts in detail.

Indeed, it may be only those who know the internal implementation that can be pleased with the similarity in form. I'll treat it like syntax sugar from now on.

**Comment by panno8M** [comment]
I added a section on [Life of Object][1] to your guide.

motivation: #120 

[1]: https://github.com/godot-nim/gdext-nim/wiki/Coding-Quick-Guide#life-of-object
