### ISSUE TITLE
New update crashing editor

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godot-nim/gdext-nim#107]
EDIT: I completely deleted my nimble and re-installed everything (also deleted .godot and recompiled) crashing still happens. Here's a strace: [dtc_strace.txt](https://github.com/user-attachments/files/17449766/dtc_strace.txt)

Now creates `linux/debug/libbootstrap.so` inside lib, whereas the expected location is `libcore.so`.

Additionally, moving+renaming this seems to work yet also freezes my editor as soon as it's loaded. Before doing so, the old library was actually still working (despite Godot+gdext-nim updates) with me trying to fix constant error messages (`needs to be normalized` etc) before I noticed that my changes were having no effect.

**Comment by panno8M** [comment]
This is a specification. Please change the .gdextension path in your project.

```ini
[libraries]

linux.debug = "res://nim/lib/linux/debug/libbootstrap.so"
windows.debug = "res://nim/lib/windows/debug/bootstrap.dll"
macos.debug = "res://./nim/lib/macos/debug/libbootstrap.dylib"

linux.release = "res://nim/lib/linux/release/libbootstrap.so"
windows.release = "res://nim/lib/windows/release/bootstrap.dll"
macos.release = "res://./nim/lib/macos/release/libbootstrap.dylib"
```

The issue of freezing is a concern. If it is related to loading libraries, once you delete res://.godot/ it may work.

Would like a detailed report.

**Comment by insomniacUNDERSCORElemon** [comment]
Now it actually crashes. Not sure which is relevant/useful:
A bunch of this: `typeshift.nim decode`

`Error: call depth limit reached in a debug build (2000 function calls). You can change it with -d:nimCallDepthLimit=<int> but really try to avoid deep recursions instead.`

A bunch of this (with different node names) too: `ERROR: BUG: Unreferenced static string to 0`

**Comment by panno8M** [comment]
I followed your suggestion and changed the package configuration of gdext, so that may be the cause as well. Please edit `$HOME/.nimble/nimbledata2.json`(delete elements related to gdext) and remove `$HOME/.nimble/pkgs2/gdext.*` and try reinstalling.

You can send me a zip file to investigate the cause.

> > This is a specification. Please change the .gdextension path in your project.
> 
> If you remember, dropping the debug/release split was your idea at one point (though I don't think I could find it to quote that).

I remember. But the context has changed since then.
I just **couldn't** separate them at that time because I didn't know how to get whether Nim was trying to target debug or release.

**Comment by insomniacUNDERSCORElemon** [comment]
> changed the package configuration of gdext, so that may be the cause as well. Please edit

I tried this and it didn't fix the issue. Either this is persistent (requiring of deleting even more) or it is something else. I have not tried another project yet, though I would hope an issue like this wouldn't come from a project especially without specifying as such.

Though being related to the change seems very likely to me.

**Comment by panno8M** [comment]
If you send me any (or all) of the following three items, I will be able to resolve the issue:

* A stack trace of the area in question (output showing in what order the calls were made and on what line of the file the problem occurred)
* Minimal source code to reproduce the problem
* Zip file of the project

There is a lack of information and it is difficult to determine the problem at present. So far, we have not identified this problem in test or any demo.

**Comment by insomniacUNDERSCORElemon** [comment]
A small update, I have just tested with both demos (freshly downloaded+compiled) and both exhibit the same crashing issue.

I will try to uninstall and more thoroughly clean things out to see if I can get it working.

**Comment by panno8M** [comment]
> Error: call depth limit reached in a debug build (2000 function calls). You can change it with -d:nimCallDepthLimit=<int> but really try to avoid deep recursions instead.

What file's, what line of, what function is saying this message? If you are building without `-d:release`, Nim should show this as a stack trace.

**Comment by insomniacUNDERSCORElemon** [comment]
> What file's, what line of, what function is saying this message? If you are building without `-d:release`, Nim should show this as a stack trace.

I don't know, no line numbers where I got that. Did you see the full strace I put in the top of the issue?

But for the basic traceback, this is the first-reported thing:

`gdext-0.2.2-75a4e118c1b779091b2434624c43e30defdb33d9/gdext/classes/gdnode.nim(9) process`

Then 

`gdext-0.2.2-75a4e118c1b779091b2434624c43e30defdb33d9/gdext/core/typeshift.nim(118) decode`

The block the quoted line is from:

```
/home/user/.nimble/pkgs2/gdext-0.2.2-75a4e118c1b779091b2434624c43e30defdb33d9/gdext/core/typeshift.nim decode
Error: call depth limit reached in a debug build (2000 function calls). You can change it with -d:nimCallDepthLimit=<int> but really try to avoid deep recursions instead.
ERROR: BUG: Unreferenced static string to 0: luminance_buffers
   at: unref (core/string/string_name.cpp:127)

```

As mentioned before, a bunch of typeshift and static string to 0 issues, so this seems more like the results not a cause.

Unless it is that string_name.cpp causing it. I should note that I did update before this, and Godot was one of the things updated (though it's still 4.3, specifically 4.3-5 ([view changes](https://gitlab.archlinux.org/archlinux/packaging/packages/godot/-/commits/main))) Note that I'm not sure what exact version I was on before as I don't frequently update my system, so it is possible the issue is not from the -5 version.

**Comment by panno8M** [comment]
I have fixed the likely cause of the problem. Run the following command to install the patched version and try again:

```bash
nimble uninstall gdext
nimble install https://github.com/godot-nim/gdext-nim@"#107-new-update-crashing-editor"
```

**Comment by insomniacUNDERSCORElemon** [comment]
> I have fixed the likely cause of the problem. Run the following command to install the patched version and try again:
> 
> ```shell
> nimble uninstall gdext
> nimble install https://github.com/godot-nim/gdext-nim@"#107-new-update-crashing-editor"
> ```

Better, DTC now runs, but my test project crashes when running (thankfully no editor crash) and gives no output error.

```
ready!
Traceback (most recent call last)
/home/username/.nimble/pkgs2/gdext-0.2.2-b2be8a33794268cbf35c674ad478c71e1cee35cc/gdext/classes/gdnode.nim(14) physicsProcess
/home/username/.nimble/pkgs2/gdext-0.2.2-b2be8a33794268cbf35c674ad478c71e1cee35cc/gdext/classes/gdnode.nim(12) physicsProcess
/run/media/username/fast_storage/godot4_new/nim/blam/nim/src/player.nim(33) physicsProcess
/home/username/.nimble/pkgs2/gdext-0.2.2-b2be8a33794268cbf35c674ad478c71e1cee35cc/gdext/classes/gdinput.nim(73) getActionStrength
/home/username/.nimble/pkgs2/gdext-0.2.2-b2be8a33794268cbf35c674ad478c71e1cee35cc/gdext/coronation/header/classes.nim(37) ptrcall
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

```

This was the 3D one, so probably why. Such as the getActionStrength, which as I've mentioned I've used to test analog control with a controller.

**Comment by panno8M** [comment]
This appears to be due to self.Input being nil.

Try simply replacing `self.Input` with `Input` and removing the Input member variable from the Player type definition.

An update a while ago made it possible to treat type names as singleton instances as in GDScript, so that should work.

```nim
import gdext
import gdext/classes / [gdCharacterBody3D, gdInput, gdSceneTree]

type Player* = ptr object of CharacterBody3D
  velocity:Vector3
  speed:float32
  look_speed:float32
  camera:Camera3D

proc vec_mult(vec:Vector3, num:float64):Vector3 =
  return [(vec.*x * num).float32, (vec.*y * num).float32, (vec.*z * num).float32]

proc vec_replace_y(vec:Vector3, num:float32):Vector3 =
  return [(vec.*x).float32, (num).float32, (vec.*z).float32]


method ready(self:Player) {.gdsync.} =
  if Engine.isEditorHint: return #running code in the editor may produce unintented scene changes, even if nodes are hidden
  self.speed = 250.0'f32

  self.look_speed = 1.5'f32
  self.camera = self/"view" as Camera3D
  Input.setMouseMode(mouseModeCaptured)
  print "ready!"

method physicsProcess(self:Player, delta:float64) {.gdsync.} =
  if Engine.isEditorHint: return

  var move_direction:Vector3
  var look_direction:Vector3

  look_direction.*y = Input.getActionStrength("look_left") - Input.getActionStrength("look_right")
  self.setRotation([0.0'f32, (self.rotation.*y + (look_direction.*y * self.look_speed * delta)).float32, 0.0'f32])
  # if added, vertical look must use camera (or other camera rig) rotation
  look_direction.*x = Input.getActionStrength("look_down") - Input.getActionStrength("look_up")
  self.camera.setRotation([(self.camera.rotation.*x + (look_direction.*x * self.look_speed * delta)).float32, 0.0'f32, 0.0'f32])


  let gravity:Vector3 = [0.0, (-9.8 * 60.0) * delta, 0.0]
  self.velocity = vec_mult(self.velocity, delta)

  #if Input.isAnythingPressed:
  move_direction.*x =
    Input.getActionStrength("move_right") - Input.getActionStrength("move_left")
  move_direction.*z =
    Input.getActionStrength("move_backward") - Input.getActionStrength("move_forward")
  move_direction = move_direction.rotated(Vector3_Up, self.rotation.*y).normalized #for non-analog

  self.velocity.*x = move_direction.*x * (self.speed * delta)
  self.velocity.*z = move_direction.*z * (self.speed * delta)

  if Input.isActionPressed "jump":
    self.velocity.*y += self.speed

  if self.isOnFloor: self.setVelocity(self.velocity)
  else:
    self.velocity = vec_replace_y(self.velocity, gravity.*y)
    #self.velocity = vec_replace_y(self.velocity, (gravity.*y + self.velocity.*y)) #jetpack, change jump velocity too
    self.velocity.*y += (Input.getActionStrength("right_trigger") * self.speed * 5.0) * delta #jetpack
    if Input.isActionPressed("hover"): self.velocity = vec_replace_y(self.velocity, math.max(0.0'f32, self.velocity.*y))
    self.setVelocity(self.velocity)
  discard self.moveAndSlide()
  if Input.isActionJustPressed "ui_cancel": Input.setMouseMode(mouseModeVisible)
  if self.position.*y < -4.0: self.getTree.quit() #voidquit
```

**Comment by insomniacUNDERSCORElemon** [comment]
> This appears to be due to self.Input being nil.
> An update a while ago made it possible to treat type names as singleton instances as in GDScript, so that should work.

Yeah, I missed that change.  Not great with the errorless crash, though.

Not sure if the `Sync` thing is something normal users should be using, or if you should have some code change log (that is more direct than seeking through commits, as each change will be only 1 instance).
