### ISSUE TITLE
How does testing work?

### ISSUE THREAD

**Issue by xix-xeaon** [godot-nim/gdext-nim#114]
I don't have a lot of experience with different kinds of test setups, and I can't understand the one in this project.

I would expect to be able to run `nimble test` to run all tests, but because a task with the name _test_ has been defined it instead only executes that task. This task is supposed to compile a test project which imports the tests, but it seems it does not - I've deliberately put syntax errors in the files and it makes no difference. It does run the test project with Godot but this apparently proves very little about the correctness.

If I remove the _test_ task, then `nimble test` does not find any tests, because it expects them in a folder called `tests` (plural). If I change this it just says it's passed all tests. I'm assuming it still doesn't actually find the real tests.

I would also expect to be able to run the individual test files with `nim c -r`. Since they use the standard unittest module and it's convenient to run only the relevant tests when you're working on that part. But the errors I got didn't make any sense until I found that the test `config.nims` used the incorrect path `"../../gdext/src"` (it should be `"../../src"`). However, since the project is setup to compile as a library (and `buildconf.nim` enforces this) it can't actually run.

I don't know what the best setup for testing this kind of project is, but it does appear to me that it's currently not working.

**Comment by panno8M** [comment]
I was indeed wrong about the path to gdext and have corrected it. (I have a nimble.paths file in my local environment, so that seems to have taken precedence.)

As for how to run the test, `gdextwiz run test` would run with a single Nim version, and `nimble test` would run with all supported Nim versions. (This was changed within the PR above.)
