### ISSUE TITLE
Making Nim variables visible to GDScript publicly without needing to be exported to the editor.

### ISSUE THREAD

**Issue by othd06** [godot-nim/gdext-nim#117]
I have a node class defined in Nim similarly to as follows:
`type myClass* = ptr object of Node
    target* : Node`
and I would like to alter it from a GDScript node as follows:
`myClass.target = self`
but this doesn't work unless I instead write my Nim class as:
`type myClass* = ptr object of Node
    target* {.gdexport.}: Node`
but this exports the variable to the editor which I don't (ideally) want to do. it would be useful if there were some pragma to make the variable visible to GDScript but not exported to the editor.

**Comment by panno8M** [comment]
Have you tried `gdexport_storage`? This is a port of [`@export_storage`][1] from GDScript.

[1]: https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export-storage

#### Examples:

```nim
type myClass* = ptr object of Node
    target* {.gdexport_storage.}: Node
```

#### Markdown tips:

If you want to attach an Nim code, try writing:

<span>
```nim <br>
type myClass* = ptr object of Node <br>
&nbsp;&nbsp;target* {.gdexport_storage.}: Node<br>
```
</span>

**Comment by othd06** [comment]
> Have you tried `gdexport_storage`? This is a port of [`@export_storage`][1] from GDScript.
> 
> [1]: https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-annotation-export-storage
> 
> #### Examples:
> 
> ```nim
> type myClass* = ptr object of Node
>     target* {.gdexport_storage.}: Node
> ```
> 
> #### Markdown tips:
> 
> If you want to attach an Nim code, try writing:
> 
> <span>
> ```nim <br>
> type myClass* = ptr object of Node <br>
> &nbsp;&nbsp;target* {.gdexport_storage.}: Node<br>
> ```
> </span>
> 

No but thank you so much. That looks like exactly what I want. I thought there might be something like that but because I couldn't for the life of me work out what I thought even if there was, at least if it was a closed issue other people would be able to find the solution easily. Anyway, thank you that's super helpful and sorry for needing to ask it here.
