### ISSUE TITLE
Thanks for your guys nice work.

### ISSUE THREAD

**Issue by zhmt** [godot-nim/gdext-nim#119]
I am trying to remake my game with gdext-nim, I have tested some example, very nice. 
Big thanks for your guys nice work.
close this issue when you guys see it.

**Comment by panno8M** [comment]
Thank you very much. It makes me happy to have started the project when I can actually hear it as a voice.
Right now this project is very settled, but I am always ready to respond to your requests and bug reports.

I thank you again and close this issue,
