### ISSUE TITLE
Is Node created as managed object or unmaged?

### ISSUE THREAD

**Issue by zhmt** [godot-nim/gdext-nim#120]
If it is created as unmaged object, then fields like string  defined in sub class of Node will be memory leaked.

**Comment by panno8M** [comment]
Since nim refs are not available for classes derived from Object, you must call `destroy` manually.

Example:

```nim
var node = instantiate(Node, "MyNode")
destroy node
```
If this does not work, please post a concrete code snippet. I can fix it if it is a bug, or offer a fix if there is a problem with the process.

**Comment by zhmt** [comment]
I have tested with desctructor of object, destructor has been call,  It means there is no memory leak.
Sorry , I am studying nim and gdext-nim at the same time, maybe I misunderstand about traced object and untraced object.

https://nim-lang.org/docs/manual.html#types-mixing-gc-ed-memory-with-nimptr

**Comment by zhmt** [comment]
```nim
type TestObj =  object
  
proc `=destroy`(x: TestObj) =
  print("destroyed")

type ShowFps* = ptr object of Label
  time : float = 0
  cd : float = 1
  testObj: TestObj

method ready(self:ShowFps) {.gdsync.} =
  if Engine.isEditorHint: return 
  self.testObj = TestObj()

method process(self :ShowFps, delta :float) {.gdsync.} =
    if Engine.isEditorHint: return
    self.time += delta
    if self.time > self.cd:
      self.text = "FPS: " & $Engine.getFramesPerSecond()
      self.time = 0

type GodotMain* = ptr object of Node

method ready(self:GodotMain) {.gdsync.} =
  if Engine.isEditorHint: return 
  var tmp = instantiate(ShowFps, "ShowFps") as Label;
  destroy tmp;
```

**Comment by zhmt** [comment]
All nodes was implemented as traced obejct, then I can use any third library  freely without worrying about memory leak. Thanks for you guys' nice work.
