### ISSUE TITLE
Bind to other node signals cause crash when hotreload

### ISSUE THREAD

**Issue by xix-xeaon** [godot-nim/gdext-nim#123]
Connecting to signals in the same node has no problems. But I'm using nodes in the editor for configuring procedural generation. When I make changes the nodes they emit a "changed" signal. A parent node has connected to these signals to detect changes and regenerate the level.

However, as soon the editor reloads the extension after compilation it crashes with `SIGSEGV: Illegal storage access.`. If I remove the line in the parent node that connects to the child signals then it doesn't crash. Might be solved by having all signals get disconnected when the extension is unloaded.

**Comment by panno8M** [comment]
@xix-xeaon 
The test code reproduced based on your report is in testproject/editor.
Please let me know if there are any errors or additions.

**Comment by xix-xeaon** [comment]
Did your test project fail before this fix? In either case, this fix does not fix the problem in my project. I tried creating a reproduction test project but was unable. I may have misunderstood the problem, I'll have to do some more debugging.

**Comment by panno8M** [comment]
Yes. There was a bug that caused hot reloading to fail if a user-defined class was requested as an argument.

Does Nim output a stack trace before or after the SIGSEGV error? Or, is it possible that a previous version of the library remains and is being referenced?

**Comment by xix-xeaon** [comment]
Well, I was wrong about the cause of this bug. The parent node has a _gdexport_ property for choosing the MeshInstance3D which contains the hightmap to be manipulated, and guarding access to this property with a `isNil` check solved the problem.

It seems that when the extension is reloaded, all the properties on the child are set first which triggers the change signal which is still connected to the parent, causing the generation function on the parent to run. **However**, at this point in time, the properties on the _parent_ have not yet been set, and the reference to the heightmap is nil.

It is only after all the properties on the children have been set (and their setters have been called, as well as the functions connected to the signals that they emit) that the parent properties are finally set.

Essentially, during the reload all properties momentarily become unset, so you can't depend on properties on other nodes having been set yet, even though they're supposed to have a value. I would assume this is simply how Godot works and not a fault of gdext-nim.
