### ISSUE TITLE
`printerr(strToVar("string"))` outputs <null> in console

### ISSUE THREAD

**Issue by morganholly** [godot-nim/gdext-nim#127]
`printerr(strToVar("string"))` outputs <null> in console. am i doing something wrong?

**Comment by panno8M** [comment]
godot's `str_to_var` is like `eval` so to speak.
https://docs.godotengine.org/en/stable/classes/class_@globalscope.html#class-globalscope-method-str-to-var

If you want it to work with `str_to_val`, the statement would be as follows.

```nim
printerr(strToVar("\"string\""))
```

However, if you simply want to create a Variant that represents a string, I suggest you use `variant()` instead.

```nim
printerr variant("string")
```

**Comment by panno8M** [comment]
I've added Variant section to the Coding Quick Guide on the wiki. See also that.
https://github.com/godot-nim/gdext-nim/wiki/Coding-Quick-Guide#variant

**Comment by morganholly** [comment]
ah ok thanks
