### ISSUE TITLE
How to load binary resource files?

### ISSUE THREAD

**Issue by zhmt** [godot-nim/gdext-nim#129]
I have some binary resource files(it is compressed , encrypted), they are loaded like this in c# :
```c#
var data = Godot.FileAccess.GetFileAsBytes(path);
// data is a plain c# byte array, like seq[byte]

```
I got a PackedByteArray in nim, but how can I retrieve seq[byte] from it? I found no related API .

Thanks for your help in advance.

**Comment by panno8M** [comment]
HACK: You can get `UncheckedArray[byte]` by accessing the `data_unsafe` property, although this depends on Godot's internal implementation and may not be available in the future.

```nim
import std/sequtils
let bytes: PackedByteArray = FileAccess.getFileAsBytes(path)
let s: seq[byte] = bytes.dataUnsafe.toOpenArray(0, bytes.size-1).toSeq
```

**Comment by panno8M** [comment]
The above features are supported in 0.3.0.

**Comment by zhmt** [comment]
> The above feature is supported in 0.3.0.

Nice work!!!
