### ISSUE TITLE
set a StandardMaterial3D crash?

### ISSUE THREAD

**Issue by noideaforaccountname** [godot-nim/gdext-nim#134]
Hi, now CSGSphere3D work, thanks.
when i try to set a StandardMaterial3D looks like crash:

```nim
  let s: CSGSphere3D = instantiate CSGSphere3D
  let mat: GdRef[StandardMaterial3D] = instantiate StandardMaterial3D
  mat[].setAlbedo(color(0, 0, 0.9))
  s.material = mat as GdRef[Material]
``` 
i wrote this "as GdRef[..." like written in wiki, is is correct? it compiles without error.

merry christmas

**Comment by panno8M** [comment]
Problem identified.

It started working when I created the material in the editor beforehand and loaded it, so it is probably a bug in the library.
It will take some time to determine the cause. I will share a snippet that loads the material, so please use that instead until we make progress:

```nim
let s : CSGSphere3D = instantiate CSGSphere3D
s.material = ResourceLoader.load("res://path/to/material.tres") as GdRef[Material]
```
