### ISSUE TITLE
I'm having trouble building the dodge_the_creep demo

### ISSUE THREAD

**Issue by Ardi-san** [godot-nim/gdext-nim#45]
Godot error

```
 platform/windows/os_windows.cpp:383 - Condition "!FileAccess::exists(path)" is true. Returning: ERR_FILE_NOT_FOUND
  GDExtension dynamic library not found: D:/Documents/Godot/demo-main/dodge_the_creeps_2d/core/lib/libcore.dll
  Failed loading resource: res://core/core.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  Cannot get class 'Main'.
  Cannot get class 'Player'.
  Cannot get class 'Hud'.
```

When I build it creates a lib folder that contains "core.dll" at this location so I'm not too sure what the issue could be.

**Comment by insomniacUNDERSCORElemon** [comment]
It should be creating `libcore.so` not `core.so`, there must be some issue with `.toDll` having a different behavior on Windows.

The easiest way to fix this on your machine would be to rename the library.

**Comment by panno8M** [comment]
@Ardi-san 
please pull repo and try again.

**Comment by Ardi-san** [comment]
renaming before didn't work for me. Pull repo and it still isn't working for me sadly.
  
`Make sure resources have been imported by opening the project in the editor at least once`

This didn't do the trick either...

here is the new error message:

``` Can't open dynamic library: D:/Documents/Godot/demo-main/dodge_the_creeps_2d/core/lib/~core.dll. Error: Error 126: The specified module could not be found..
  core/extension/gdextension.cpp:719 - GDExtension dynamic library not found: D:/Documents/Godot/demo-main/dodge_the_creeps_2d/core/lib/~core.dll
  Failed loading resource: res://core/core.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
  Cannot get class 'Main'.
  Cannot get class 'Player'.
  Cannot get class 'Hud'.````

**Comment by panno8M** [comment]
@Ardi-san 
As far as the error is concerned, the core/core.gdextension file seems to be recognized successfully.
In order for the project to work, the dll file specified by `windows = ` in the core.gdextension file must actually exist.
The expected location (as specified in the .gdextension file) is core/lib/core.dll. Make sure you have the binary there. If it is somewhere else, rename it.
If it is nowhere to be found, it probably has not been built. Run `nim c core/bootstrap` or `gdextwiz build` to compile the binary.

If the above does not change the situation, please report back with a screenshot of the project directory and the contents of core/core.gdextension.

**Comment by Ardi-san** [comment]
![Screenshot 2024-08-11 054934](https://github.com/user-attachments/assets/8e3c6660-56cc-4428-81f1-06183e68f754)

**Comment by panno8M** [comment]
Thanks for the report.
I will test it on my end with windows. It will take some time, but please wait.

**Comment by panno8M** [comment]
@Ardi-san 
Resolved. As it turns out, it was the compiler: nim uses the mingw compiler by default, which is mismatched with godot. To solve the problem, we need to use msvc instead.

Please follow the directions below:
(I'm going to post this chart on the wiki, so if one doesn't work, please report it so we can help improve it)

```mermaid
flowchart TD
    A{Have visual studio or\nvisual studio build tools\nwith c++ support}
    A --> |Yes| B{"Path to the compiler is available \n(`cl` command is ready)"}
    A --> |No| A1["install Build Tools for Visual Studio 2022 [1]\nwith check C++ development"]
    A1 --> B
    B --> |No| B1["add user path to:\nC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\XX.XX.XXXXX\bin\HostX64\x64\n[2]"]
    B --> |yes| C["add `--cc:vcc` to config.nims"]
    B1 --> C
    C --> D["gdextwiz build && godot"]
```

1: https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2022  
2: I installed Build Tools, so your path may be different if you are using Visual Studio.

**Comment by Ardi-san** [comment]
Thanks for fixing the problem. Everything works great!
