### ISSUE TITLE
Support macos

### ISSUE THREAD

**Issue by panno8M** [godot-nim/gdext-nim#70]
I don't have a macos environment, so I need contributions of reports on how it works on macos, PR to make it work on macos, etc.

**Comment by gushromp** [comment]
I tried the demo projects (Dodge the Creeps, decbinhex4). Works out of the box. 
The only thing needed to be added was 
```
[libraries]
...
macos.debug = "res://nim/project_name/lib/macos/debug/libbootstrap.dylib"
macos.release = "res://nim/project_name/lib/macos/release/libbootstrap.dylib"
```
to the `.gdextension` files

There is only one warning when compiling either via `nim c bootstrap.nim` or `gdextwiz build-all`:
`ld: warning: ignoring duplicate libraries: '-lm'`

---

The only thing (that I found so far) that doesn't work is hot reload. Though I suspect this is a Godot issue and not this extension. https://github.com/godotengine/godot/issues/90108

The reason why I think this is the case is because, when recompiling and attempting to hot-reload, neither 
```nim
  proc entryPoint*(p_get_proc_address: InterfaceGetProcAddress; p_library: ClassLibraryPtr; r_initialization: ptr Initialization): Bool {.gdcall, exportc: Extension.entrySymbol, dynlib.} = once:
```

nor 

```nim
 {.emit: "N_LIB_EXPORT N_CDECL(void, NimMain)(void);".}
  proc initialize(userdata: pointer; p_level: InitializationLevel) {.gdcall.} =
```

get called, and this error is returned: 
`core/extension/gdextension.cpp:821 - GDExtension initialization function 'init_library' returned an error.`

**Comment by panno8M** [comment]
@gushromp 
Thank you for the report. It was helpful.

### Regarding hot reloading:

Just to confirm, is this error caused by a hot reload rather than a normal load?
A hot reload is a load that runs when you recompile an extension with the editor running and then refocus the editor.
I would like to ask this happens at editor startup or project execution or not.

**Comment by alt-ivan** [comment]
>  A hot reload is a load that runs when you recompile an extension with the editor running and then refocus the editor.

Yes, I meant this kind of hot reload. Reloading the project manually via Project -> Reload project works fine

**Comment by gushromp** [comment]
@panno8M 

>  A hot reload is a load that runs when you recompile an extension with the editor running and then refocus the editor.

Yes, I meant this kind of hot reload. Reloading the project manually via Project -> Reload project works fine

**Comment by gushromp** [comment]
Oh and I forgot to mention, `choosenim` installs the X86_64 version of Nim and runs via Rosetta. Obviously the dylibs produced for that arch don't work with Godot 4.3 official download which is AArch64. So I installed Nim via Homebrew instead.

**Comment by panno8M** [comment]
### Hot reloading

> The reason why I think this is the case is because, when recompiling and attempting to hot-reload, neither...

`init_library` is the entry symbol for gdextension, as defined by gdext-nim. （It is specified in the `exportc: Extension.entrySymbol` pragma).

`core/extension/gdextension.cpp:821 - GDExtension initialization function 'init_library' returned an error.`
This error means that we can expect some exception to be thrown in the entryPoint function.
I have pushed a fix to main that prints out the contents of the exception that should have been thrown, and I would appreciate it if you could test it again using this.

### Choosenim/Homebrew

If we were to guide you from the library on this, is it enough to add a sentence that “For macos, use Homebrew, not choosenim.”? Any ideas?

**Comment by gushromp** [comment]
Re Choosenim/Homebrew: I believe that the best approach would be stating that a native AArch64/ARM64 build of Nim is required, and that choosenim installs a x86_64 build emulated via Rosetta. So you can point the users to using the build provided by Homebrew, but at least they will know _why_ :) 

> I have pushed a fix to main that prints out the contents of the exception that should have been thrown, and I would appreciate it if you could test it again using this.

I have already tried various forms of logging, that's how I deduced that `entryPoint` is not called again after reload.
I will try your new commit as well but I assume it will lead to the same results.

Basically I added the following logs by appending to a file:
```
proc log(s: string) = 
  let f = open("some_log_location.log", fmAppend)
  writeLine(f, s)
  close(f)
  
  ...

 {.emit: "N_LIB_EXPORT N_CDECL(void, NimMain)(void);".}
  proc initialize(userdata: pointer; p_level: InitializationLevel) {.gdcall.} =
    log "Init"
    ...

  proc deinitialize(userdata: pointer; p_level: InitializationLevel) {.gdcall.} =
    log "Deinit"
    ...
    
  proc entryPoint*(p_get_proc_address: InterfaceGetProcAddress; p_library: ClassLibraryPtr; r_initialization: ptr Initialization): Bool {.gdcall, exportc: Extension.entrySymbol, dynlib.} = once:
    log "Entry"
    ...

```

And the logs produced by this are as follows (after loading the project and performing one hot-reload attempt):

```
Entry
Init
Init
Init
Init
Deinit
Deinit
Deinit
Deinit
```

**Comment by gushromp** [comment]
@panno8M 
I tried your latest commit as well, to the same result. Unfortunately this seems to be a Godot issue that affects mac.
Again the entry function isn't even called on hot reload, and in the attached image you can see the sole error message.

I had a hunch that it could perhaps be related to ASLR/PIE. So I compiled with `--passL:"-wL,-no_pie"` but unfortunately that didn't help either :( 

<img width="1170" alt="slika" src="https://github.com/user-attachments/assets/c0ecdbd6-6827-45a0-b3c8-2807c7437d87">

**Comment by panno8M** [comment]
@gushromp 
Thanks again for your detailed report. I finally understand what you meant when you said it could be a problem on the engine side.

> I will try with a godot-cpp reloadable sample to try and reproduce the issue just to make sure.

I would very much appreciate it.
I remember that the godot-cpp build didn't update dynlib without adding a diff to the source. (There may be an option like force-compile, though...)

### Invitation

If I may, I would like to ask you to join godot-nim org. I'd like you to maintain (or report on the operation of) it for mac when you feel like it. You don't have to participate in development.

**Comment by gushromp** [comment]
@panno8M 
Thank you, I accepted the invitation.

I tried SwiftGodot which also fails, though in their case it seems they have not implemented unregistering classes upon reload or I didn't use the correct `make` subcommand.

Then I tried godot-rust and... hot reloading works :) I will try to see what they do differently and if it can be applied to gdext-nim

**Comment by panno8M** [comment]
I copy.
If the internal processing of gdext is difficult to understand, I can create a graph of the process upon request.  Whether you want to or not, I'm planning on making one eventually though.

**Comment by gushromp** [comment]
I made some progress in finding the "culprit" so to speak. It's the `once` template used in the entry point.
Like that issue I linked earlier states, on mac it seems the actual library isn't unloaded and re-loaded. 

However this still means that hot-reloading doesn't work. I no longer get the error and can confirm the entry point is called on hot-reload. But since the actual library isn't reloaded we still get the old one in memory, so any changes made will not be reflected until manual project reload.

I'm still looking into the Rust Godot codebase to see how they have mitigated this issue.

**Comment by gushromp** [comment]
I finally found a way to make it work :) 

https://github.com/godotengine/godot/issues/90108#issuecomment-2296583560

This user was right, putting a relative path to the libraries in the `.gdextension` file causes it to be properly reloaded!
What a dumb thing/bug/behavior, whatever you want to call it :)

So in the Dodge the Creeps demo, I simply moved all godot files to a `godot` subfolder, moved `nim.gdextension` to this new folder and put this in the .gdextension:

```
[configuration]

entry_symbol = "init_library"
compatibility_minimum = 4.3
reloadable = true

[libraries]

linux.debug = "res://../nim/lib/linux/debug/libbootstrap.so"
windows.debug = "res://../nim/lib/windows/debug/bootstrap.dll"
macos.debug = "res://../nim/lib/macos/debug/libbootstrap.dylib"

linux.release = "res://../nim/lib/linux/release/libbootstrap.so"
windows.release = "res://../nim/lib/windows/release/bootstrap.dll"
macos.release = "res://../nim/lib/macos/release/libbootstrap.dylib"
```

And now it works!

**Comment by panno8M** [comment]
Awesome!

> P.S. If you want I could make a PR to the demo repository with the new folder structure

Please do so, as we would like to note for the record that this is your contribution.
In addition to the several files in demo, gdext-nim also has the following files to be changed:

* gdext-nim/test/nim/tests.gdextension
* gdext-nim/src/wizard/subcommands/extension/template/.gdextension
* 
Other than the .gdextension file, were there any other changes?

BTW what happens if change the paths to "res://./nim/..." without changing the current directory structure?

**Comment by gushromp** [comment]
@panno8M 
> BTW what happens if change the paths to "res://./lib/..." without changing the current directory structure?

This works as well! So that's what I ended up doing in the `demo` repo change commit. It's less invasive than changing the entire folder structure.

> Other than the .gdextension file, were there any other changes?

No :) Just the `.gdextension` files

**Comment by gushromp** [comment]
I have created the respective PRs. As an additional node - I don't know if anyone tested hot-reload of `gdext-nim` on Linux? Because according to that Godot issue on GitHub, the same problem should affect Linux as well, in that case the same "fix" should likely be applied as well.

**Comment by panno8M** [comment]
I have been developing this library mainly on linux and hot-reloading was working **tentatively**. At least it didn't happen that the dynamic library didn't load.

Anyway, thanks to you I can now clearly state that it works on macos. I close this issue with gratitude.

**Comment by gushromp** [comment]
@panno8M 

Regarding hot-reload failing intermittently on Linux, I saw `godot-rust` implement some workarounds just for Linux hot reload. Might be useful looking into: https://github.com/godot-rust/gdext/blob/e416a5520c1fb439cac03906ea04acdf26e3453f/godot-core/src/init/mod.rs#L27
