### ISSUE TITLE
Make compile duration faster

### ISSUE THREAD

**Issue by panno8M** [godot-nim/gdext-nim#94]
### Motivation

Currently, compilation takes several seconds to several tens of seconds of non-negligible time, which is quite painful when considering actual game development.

According to the Nim RFC, incremental compilation will be officially supported starting with Nim 2.2. There is a way to wait until then, but there seems to be a correlation between compile time and the thickness of the metaprogramming layer. Its duration shorter means that it operates with more simple mechanism, and it would also act as a barometer of project maintainability.

### Description

Most effective would be tuning to extended class helper macros, especially function registration macros. In my environment, it takes about 3 seconds to compile the entire test, whereas it takes about 0.7 seconds if all class imports/registrations are commented out. That's how heavy the registration process is at the moment.

Other measures that could be taken include precompiling the library backend or incorporating NimScript, as in Nim4UE.

### Environment

OS: Linux
CPU: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (6 cores, 12 threads)
CC: gcc/x86_64-pc-linux-gnu/14.2.1

### Bench

```console
$ git show --format='%H' --no-patch
8ec23b4a0f1f1d0d2a9172210190fd4530c34c5a

$ time gdextwiz build -f test
________________________________________________________
Executed in    4.22 secs    fish           external
   usr time   11.81 secs    1.31 millis   11.81 secs
   sys time    1.96 secs    0.02 millis    1.96 secs

$ time gdextwiz build test
________________________________________________________
Executed in    2.77 secs    fish           external
   usr time    2.66 secs    1.25 millis    2.66 secs
   sys time    0.10 secs    0.32 millis    0.10 secs
```

In windows11/x86_64-w64-mingw32-gcc, I believe it was about three times slower, although I did not measure it exactly.

**Comment by gushromp** [comment]
Since the bulk of the time is taken up in the Nim compilation stage, not C compilation/linking, and the Nim compiler is single threaded, another (maybe?) possible avenue to explore is compiling the individual class source files by invoking the compiler in parallel for each `nim --compileOnly:on --nimcache:PATH_TO_BOOTSTRAP_NIMCHACHE c class1[2,3,4...].nim` which would work in theory as long as each source file can be compiled standalone. The downside would of course be that RAM usage would skyrocket.

Then the only issue would be class registration but there's probably some way to automate that as well

**Comment by panno8M** [comment]
Interesting idea. However, considering the case where class1 imports class2 (inheritance, composition, etc.), it may be a bit difficult to realize.

As an example, let's assume the following case.

* classA.nim
* classB.nim -> import classA
* classC.nim -> import classA

In this case, the following processes would run in parallel.

* nim c classA # compiles classA
* nim c classB # compiles classA, classB
* nim c classC # compiles classA, classC

These examples do not negate your idea, but may be enough to make us hesitate to try.

**Comment by dawdmaow** [comment]
Maybe using Nimscript to run Nim code could work.

**Comment by insomniacUNDERSCORElemon** [comment]
> However, considering the case where class1 imports class2 (inheritance, composition, etc.), it may be a bit difficult to realize.

Could you handle this via the bootstrap file, maybe even defining scope via blocks?

```
proc register_classes {.execon: initialize_scene.} =
    block:
      register Player
      register BaseEnemy
      register BaseMenu
      register Spawner
      register BaseDoor
    block:
      register SandboxPlayer
      register EnemySkeleton
      register MenuSettings
      register DoorArena
```
Standard un-pooled could still be done normally outside of a block before/after.

**Comment by panno8M** [comment]
I examined the compile time while limiting the functionality of gdext-nim.

As a result, even with all features turned off and the library set to “do nothing,” compile time was reduced by only -0.3s (-15%).

Most of the rest seems to be spent interpreting class definition files, which is not surprising with 103709/922 (lines/files).

I'll stop thinking for once and wait for the release of [nimony](https://github.com/nim-lang/nimony) :-\
